version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app/:rw
    env_file:
      - env/cloud.env

volumes:
  app:

