version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src/:rw
    env_file:
      - env/cloud.env

volumes:
  src:

